### ISSUE TITLE
When one of `source_idx` or `target_idx` is 0, an invalid access is made here

### ISSUE THREAD

**Issue by da-x** [ajmalsiddiqui/levenshtein-diff#1]
https://github.com/ajmalsiddiqui/levenshtein-diff/blob/86afee1ce4c1063d5242e694e38c2b4422b55d73/src/edit.rs#L141

**Comment by ajmalsiddiqui** [comment]
Thank you for raising the issue. I've fixed the issue in [this commit](https://github.com/ajmalsiddiqui/levenshtein-diff/commit/f016c17a7e0a008e3012a6116f6e4dae82932636) and released the fix with version 0.2.2.
